// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obwkkzsemimptvrvjifd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9id2trenNlbWltcHR2cnZqaWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODMxMzIsImV4cCI6MjA2MDA1OTEzMn0.deA_6OO1-6XgNPid8GHo5Tz8FHeq9weEXjIaZNPVNDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);